name: Build python-ldap wheels for Windows

on:
  workflow_dispatch:

env:
  OPENSSL_VER: openssl-3.3.2
  OPENLDAP_VER: openldap-2.5.19
  PYTHONLDAP_VER: python-ldap-3.4.4
  CIBW_TEST_COMMAND: python -c"import ldap;print(ldap.__version__)"
  CIBW_SKIP: "pp* cp36* cp37*"
  MSBUILDTREATHIGHERTOOLSVERSIONASCURRENT: 1

jobs:
  build_amd64:
    name: Build AMD64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    env:
      VS_PLATFORM: x64
      OPENSSL_CONFIG: VC-WIN64A-masm
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: build_openssl.cmd
        shell: cmd
      - run: build_openldap.cmd
        shell: cmd
      - run: build_python-ldap.cmd
        shell: cmd
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: AMD64
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
